# Generated by Django 5.0.7 on 2025-06-20 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_app', '0002_citymanager_customer_porter_warehousemanager_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_packed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='is_shipped',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='out_for_delivery',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='received_at_city',
            field=models.BooleanField(default=False),
        ),
    ]
