# Generated by Django 5.0.7 on 2025-06-21 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_app', '0003_order_is_packed_order_is_shipped_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pincode', models.CharField(max_length=6)),
                ('porter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery_app.porter')),
            ],
        ),
    ]
