# Generated by Django 5.0.7 on 2025-06-21 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_app', '0004_deliveryarea'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.IntegerField(default='100'),
            preserve_default=False,
        ),
    ]
