# Generated by Django 5.0.7 on 2025-06-22 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_app', '0005_order_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehousemanager',
            name='phone',
            field=models.CharField(default='6299887765', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='warehousemanager',
            name='pincode',
            field=models.CharField(default='802204', max_length=10),
            preserve_default=False,
        ),
    ]
